# Generated by Django 5.0.6 on 2024-07-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la maladie')),
                ('nom_scientiste', models.CharField(max_length=150, verbose_name='Nom Scientifique de la maladie')),
                ('description', models.TextField(verbose_name='Description de la maladie')),
                ('symptomes', models.TextField(verbose_name='Symptômes de la maladie')),
                ('causes', models.TextField(verbose_name='Causes de la maladie')),
                ('consequences', models.TextField(verbose_name='Conséquences de la maladie')),
                ('disease_types', models.CharField(choices=[('Maladies infectieuses', 'MALADIES INFECTIEUSES'), ('Maladies non infectieuses', 'MALADIES NON INFECTIEUSES'), ('Maladies spécifiques à un organe', 'MALADIES SPÉCIFIQUES À UN ORGANE'), ('Troubles de la santé mentale', 'TROUBLES DE LA SANTÉ MENTALE'), ('Troubles du développement', 'TROUBLES DU DÉVELOPPEMENT '), ('Maladies environnementales', 'MALADIES ENVIRONNEMENTALES')], max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('role', models.TextField(verbose_name='Les effets de ce medicament.')),
                ('prix', models.PositiveIntegerField(default=0)),
                ('image', models.FileField(max_length=255, upload_to='image/produits/')),
                ('ill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.maladie', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom de la pharmacie.')),
                ('description', models.TextField(null=True, verbose_name='Situer la pharmacie')),
                ('location', models.URLField(null=True, verbose_name='Coordonnées de la pharmacie.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medications', models.ManyToManyField(to='pharmacie.medication', verbose_name='Médicaments liés à la pharmacie')),
            ],
        ),
    ]
