# Generated by Django 5.0.7 on 2024-07-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladie',
            name='prevention',
            field=models.TextField(default='sauver des vies', verbose_name='Preventions de la maladie'),
        ),
    ]
