# Generated by Django 5.0.7 on 2024-07-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_maladie_prevention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maladie',
            name='description',
        ),
    ]
