# Generated by Django 5.0.6 on 2024-07-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_remove_medication_ill_remove_medication_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.FileField(blank=True, max_length=255, upload_to='image/produits/'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='nom',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
