# Generated by Django 5.0.7 on 2024-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0005_alter_medication_image_alter_medication_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.FileField(blank=True, max_length=255, upload_to='Pahrmacien/produits/'),
        ),
    ]
