# Generated by Django 5.0.6 on 2024-07-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('patient', 'PATIENT'), ('medecin', 'MEDECIN'), ('pharmacien', 'PHARMACIEN')], default=('patient', 'PATIENT'), max_length=10)),
                ('preuve', models.FileField(max_length=255, upload_to='health/static/documents/')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
