# Generated by Django 5.0.6 on 2024-07-04 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
        ('medecin', '0001_initial'),
        ('pharmacie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='pharmacie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacie.pharmacie', verbose_name='Pharmacie'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='subSpeciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medecin.subspeciality', verbose_name='Specialite du medecin'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
