# Generated by Django 5.0.6 on 2024-07-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
        ('medecin', '0001_initial'),
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medecin.speciality', verbose_name='Specialite du medecin'),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='pharmacie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacie.pharmacie', verbose_name='Pharmacie'),
        ),
    ]
