# Generated by Django 5.0.6 on 2024-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assurance_medicale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code_assurance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='personne_a_prevenir',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel_personne_a_prevenir',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
