# Generated by Django 5.0.7 on 2024-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_patient_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='image',
            field=models.FileField(default='static/adminLTE/img/avatar5.png', max_length=255, upload_to='static/adminLTE/img/profile/'),
        ),
    ]
