# Generated by Django 5.0.7 on 2024-07-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_utilisateur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.FileField(blank=True, default='static/adminLTE/img/avatar5.png', max_length=255, upload_to='static/adminLTE/img/profile/'),
        ),
    ]
