# Generated by Django 5.0.7 on 2024-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_utilisateur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='approuverMedecin',
            field=models.BooleanField(default=False, verbose_name='Validation du medecin'),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='approuverPharmacien',
            field=models.BooleanField(default=False, verbose_name='Validation du pharmacien'),
        ),
    ]
