# Generated by Django 5.0.6 on 2024-07-18 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_alter_utilisateur_mobile'),
        ('pharmacie', '0004_remove_medication_ill_remove_medication_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacien',
            name='pharmacie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacien', to='pharmacie.pharmacie', verbose_name='Pharmacie'),
        ),
    ]
