# Generated by Django 5.0.7 on 2024-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0013_alter_utilisateur_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='verifierMedecin',
            field=models.BooleanField(default=False, verbose_name='verification du medecin'),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='verifierPharmacien',
            field=models.BooleanField(default=False, verbose_name='verification du pharmacien'),
        ),
    ]
