# Generated by Django 5.0.7 on 2024-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_medecin_verifiermedecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='preuveMedecin',
            field=models.FileField(upload_to='Medecin/'),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='preuvePharmacien',
            field=models.FileField(upload_to='Pharmacien/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.FileField(blank=True, default='static/adminLTE/img/avatar5.png', max_length=255, upload_to='profile/'),
        ),
    ]
