# Generated by Django 5.0.6 on 2024-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointement',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
