# Generated by Django 5.0.7 on 2024-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_appointement_motif_alter_appointement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointement',
            name='motif',
            field=models.CharField(default="Mal a l'aise", max_length=250),
        ),
    ]
