# Generated by Django 5.0.7 on 2024-08-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_appointement_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointement',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
