from django.urls import path
from .views import *

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard_m'),
    path('appointement/accepte-#<int:id>/', accepte, name='accepte'),
    path('appointement/refuse-<int:id>#/', refuse, name='refuse'),
    path('hospital/create/', creaHopital, name='create_hos'),
    path('hospital/read/hos-<int:id>-view/', readHopital, name='read_hos'),
    path('hospital/read/all/', readAllHopital, name='readAll_hos'),
    path('hospital/update/hos-<int:id>-view/', updHopital, name='update_hos'),
    path('hospital/delete/hos-<int:id>-view/', delHopital, name='delete_hos'),
    path('advice/create/', creaAdvice, name='create_adv'),
    path('advice/read/adv-<int:id>-view/', readAdvice, name='read_adv'),
    path('advice/read/all/', readAllAdvice, name='readAll_adv'),
    path('advice/update/adv-<int:id>-view/', updAdvice, name='update_adv'),
    path('advice/delete/adv-<int:id>-view/', delAdvice, name='delete_adv'),
    path('consigne/create/', creaConsigne, name='create_csg'),
    path('consigne/read/csg-<int:id>-view/', readConsigne, name='read_csg'),
    path('consigne/read/all/', readAllConsigne, name='readAll_csg'),
    path('consigne/update/csg-<int:id>-view/', updConsigne, name='update_csg'),
    path('consigne/delete/csg-<int:id>-view/', delConsigne, name='delete_csg'),
    path('prescription/create/', creaPrescription, name='create_prsc'),
    path('prescription/read/prsc-<int:id>-view/', readPrescription, name='read_prsc'),
    path('prescription/read/all/', readAllPrescription, name='readAll_prsc'),
    path('prescription/update/prsc-<int:id>-view/', updPrescription, name='update_prsc'),
    path('prescription/delete/prsc-<int:id>-view/', delPrescription, name='delete_prsc'),
    path('speciality/create/', creaSpeciality, name='create_spc'),
    path('speciality/read/spc-<int:id>-view/', readSpeciality, name='read_spc'),
    path('speciality/read/all/', readAllSpeciality, name='readAll_spc'),
    path('speciality/update/spc-<int:id>-view/', updSpeciality, name='update_spc'),
    path('speciality/delete/spc-<int:id>-view/', delSpeciality, name='delete_spc'),
]