# Generated by Django 5.0.7 on 2024-07-15 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_utilisateur_image'),
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnetsante',
            name='frequence_cardiaque',
        ),
        migrations.RemoveField(
            model_name='carnetsante',
            name='hospitalisation',
        ),
        migrations.RemoveField(
            model_name='carnetsante',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='carnetsante',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='carnetsante',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='carnetsante',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='carnetsante',
            name='tension_arterielle',
        ),
        migrations.RemoveField(
            model_name='hospitalisation',
            name='facture',
        ),
        migrations.AddField(
            model_name='carnetsante',
            name='hospitalisations',
            field=models.ManyToManyField(related_name='hospitalisation_patient_carnetSante', to='medecin.hospitalisation'),
        ),
        migrations.AddField(
            model_name='carnetsante',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patient_carnet', to='authentification.patient', verbose_name='Carnet_patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='frequence_cardiaque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='poids',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consultation',
            name='taille',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='consultation',
            name='temperature',
            field=models.FloatField(default=37),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tension_arterielle',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='hospitalisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medecin.hospitalisation'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='consultation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medecin.consultation'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='prixTotal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
