# Generated by Django 5.0.7 on 2024-07-29 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_medecin_verifiermedecin_and_more'),
        ('medecin', '0004_remove_consultation_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnetsante',
            name='patient',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patient_carnet', to='authentification.patient', verbose_name='Carnet_patient'),
        ),
    ]
