# Generated by Django 5.0.7 on 2024-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0005_alter_carnetsante_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalisation',
            name='accompagnant',
        ),
        migrations.RemoveField(
            model_name='hospitalisation',
            name='cause_deces',
        ),
        migrations.RemoveField(
            model_name='hospitalisation',
            name='date_deces',
        ),
        migrations.RemoveField(
            model_name='hospitalisation',
            name='date_sortie',
        ),
        migrations.RemoveField(
            model_name='hospitalisation',
            name='tel_accompagnant',
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='traitements',
            field=models.ManyToManyField(default=None, to='medecin.traitement', verbose_name=''),
        ),
    ]
