# Generated by Django 5.0.7 on 2024-07-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0006_remove_hospitalisation_accompagnant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalisation',
            name='consultation',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='medecin.consultation'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='date_resultats',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='traitements',
            field=models.ManyToManyField(blank=True, default=None, to='medecin.traitement', verbose_name=''),
        ),
    ]
