# Generated by Django 5.0.7 on 2024-07-29 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0007_alter_hospitalisation_consultation_and_more'),
        ('pharmacie', '0005_alter_medication_image_alter_medication_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_medecin', to='medecin.consultation', verbose_name='consultation du Medecin'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medications',
            field=models.ManyToManyField(blank=True, default=None, to='pharmacie.medication', verbose_name='medicaments de prescription'),
        ),
    ]
