# Generated by Django 5.0.7 on 2024-08-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0008_remove_prescription_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='consigne',
            field=models.ManyToManyField(blank=True, to='medecin.consigne', verbose_name='Les medications et leur posologie a suivre'),
        ),
    ]
