# Generated by Django 5.0.7 on 2024-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0009_alter_prescription_consigne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='image',
            field=models.FileField(max_length=255, upload_to='Medecin/conseils/'),
        ),
        migrations.AlterField(
            model_name='examenbiologique',
            name='image',
            field=models.ImageField(upload_to='Medecin/radiology/'),
        ),
    ]
